apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    nginx.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true" 
    nginx.ingress.kubernetes.io/ssl-passthrough: "true" 
spec:
  ingressClassName: nginx    
  rules:     
    - host: argocd.xxx.com
      http:
        paths:
          - path: /
            pathType: Prefix    
            backend:
              service:
                name: argocd-server
                port:
                  name: https
  tls:    
  - hosts:
    - tls-argocd-nginx
    secretName: argocd-secret   

